### ISSUE TITLE
Splash Lua script? 

### ISSUE THREAD

**Issue by jayjgal** [EdmundMartin/SplashCrawler#1]
Hi Edmund I read your blog post and I was wondering if it would be possible to run a Splash Lua script within your crawler to be able to interact with a page, doing things like simulating calls, clicking on buttons etc. I tried doing that with a function here is my code:

    def script(self, res):
        script = """
            function main(splash)
                assert(splash:go(splash.args.res))
                btn = splash:select_all('.btn-races')[3]
                btn:mouse_click)
                assert(splash:wait(1))

            end
            """

**Comment by EdmundMartin** [comment]
Hello,

Yes it's perfectly possible. The Splash server HTTP API allows you to execute a lua script by simply passing it as a parameter within the URL as a string.

An Example of the format can be found here:

http://localhost:8050/info?wait=0.5&images=1&expand=1&timeout=90.0&url={url}&lua_source={lua_source}

I'd recommend playing around with the Splash user interface in your browser should give an idea of how this is done. You may also need to return the HTML or HAR if you want to do something with the resulting page HTML. Which is done in the following way:
```
return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
```

**Comment by jayjgal** [comment]
Thanks very much!
